#!/command/with-contenv bash
# shellcheck shell=bash

if [ ${MIXMATCH_ENABLE_SCHEDULER} == "true" ]; then
    cd ${BASE_DIRECTORY} && s6-setuidgid mixmatch mixmatch run scheduler
else
    echo "scheduler service disabled to enable it set the MIXMATCH_ENABLE_SCHEDULER=true environment variable"
    exec s6-svc -Od .
fi
