[build-system]
requires = ["setuptools >= 72.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mixmatch"
version = "0.0.1"
requires-python = ">= 3.10"
dependencies = [
    "alembic==1.14.0",
    "argon2-cffi==23.1.0",
    "cachetools==5.5.0",
    "celery[sqlalchemy]==5.4.0",
    "cron-validator==1.0.8",
    "click==8.1.7",
    "essentia==2.1b6.dev1110",
    "fastapi==0.115.6",
    "fastapi-pagination==0.12.32",
    "mutagen==1.47.0",
    "numpy<2.0.0",  # required for essentia==2.1b6.dev1110
    "psycopg2-binary==2.9.10",
    "pydantic-settings==2.7.0",
    "python-multipart==0.0.19",
    "sqlmodel==0.0.22",
    "uvicorn[standard]==0.32.1"
]

[project.optional-dependencies]
dev = ["bump-my-version==0.18.3"]

[project.scripts]
mixmatch = "mixmatch.__main__:main"

[tool.setuptools.packages.find]
include = ["mixmatch", "mixmatch.*"]

[tool.bumpversion]
current_version = "0.0.1"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "mixmatch/__init__.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"
