#!/command/with-contenv bash
# shellcheck shell=bash

PUID=${MIXMATCH_PUID:-1000}
PGID=${MIXMATCH_PGID:-1000}

groupmod -o -g "$PGID" mixmatch
usermod -o -u "$PUID" mixmatch

echo "
-------------------------------------
MIXMATCH GID/UID
-------------------------------------
User uid:    $(id -u mixmatch)
User gid:    $(id -g mixmatch)
-------------------------------------
"

chown mixmatch:mixmatch ${BASE_DIRECTORY}
chown mixmatch:mixmatch -R ${IMAGE_DIRECTORY}
