#!/command/with-contenv bash
# shellcheck shell=bash

if [ ${MIXMATCH_ENABLE_API} == "true" ]; then
    cd ${BASE_DIRECTORY} && s6-setuidgid mixmatch mixmatch run server --host 0.0.0.0
else
    echo "api service disabled to enable it set the MIXMATCH_ENABLE_API=true environment variable"
    exec s6-svc -Od .
fi
