#!/command/with-contenv bash
# shellcheck shell=bash

mkdir -p ${SSL_DIRECTORY}

if [[ "${MIXMATCH_SSL_SELFSIGNED}" == "true" ]] && [[ ! -f ${SSL_DIRECTORY}/server.crt ]]; then
    openssl req -x509 -newkey rsa:4096 -nodes -keyout ${SSL_DIRECTORY}/server.key -out ${SSL_DIRECTORY}/server.crt \
    -days 3650 -subj "/CN=${MIXMATCH_HOSTNAME:-localhost}"
fi

chown -R mixmatch:mixmatch ${SSL_DIRECTORY}
