#!/command/with-contenv bash
# shellcheck shell=bash

if [ ${MIXMATCH_ENABLE_WORKER} == "true" ]; then
    cd ${BASE_DIRECTORY} && s6-setuidgid mixmatch mixmatch run worker
else
    echo "worker service disabled to enable it set the MIXMATCH_ENABLE_WORKER=true environment variable"
    exec s6-svc -Od .
fi
