name: Build, Package & Publish

on:
    push:
        branches: [ $default-branch ]
        tags: [ 'v*' ]
    pull_request:
    workflow_dispatch:

jobs:
    backend:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        env:
            DOCKERHUB_REPOSITORY: mixmatch-api
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.11
            - uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - run: python setup.py sdist
            - run: |
                  docker build --pull -t "${{ vars.DOCKERHUB_NAMESPACE }}/${{ DOCKERHUB_REPOSITORY }}:${{ github.sha }}" .
                  docker push "${{ vars.DOCKERHUB_NAMESPACE }}/${{ DOCKERHUB_REPOSITORY }}:${{ github.sha }}"
              if: github.ref_type == 'branch'
            - run: |
                  docker build --pull -t "${{ vars.DOCKERHUB_NAMESPACE }}/${{ DOCKERHUB_REPOSITORY }}:${{ github.ref_name }}" .
                  docker push "${{ vars.DOCKERHUB_NAMESPACE }}/${{ DOCKERHUB_REPOSITORY }}:${{ github.ref_name }}"
              if: github.ref_type == 'tag'
            - run: |
                  docker build --pull -t "${{ vars.DOCKERHUB_NAMESPACE }}/${{ DOCKERHUB_REPOSITORY }}:latest" .
                  docker push "${{ vars.DOCKERHUB_NAMESPACE }}/${{ DOCKERHUB_REPOSITORY }}:latest"
              if: github.ref_type == 'tag'
